```{r setup}
#| message: false
#| warning: false
library(tidyverse)
```

## Productivity {.unnumbered}

For productivity we can use the general recovery model as described in @Maurent2023.

$$ prod = \theta_0 + (\theta_{\infty} -\theta_0)\cdot(STP+LTP)$$

$$LTP = 1 - exp(-\lambda\cdot t) $$

$$STP = \delta \cdot \left(\frac{t}{\tau} \cdot exp\left(1 - \frac{t}{\tau}\right)\right)^2 $$ Below we show the productivity in four sites that have been remeasured for multiple decades.

```{r}
data <- read.csv("data/derived_data/aggregated_data.csv")

control_string <- "unlogged|to be logged|old-growth|control|natural"
silv_string <- "treatment|devital|thinning"

plot_info <-
  read.csv("data/raw_data/bioforest-plot-information.csv") |>
  mutate(site = ifelse(site == "BAFOG", "Bafog", site)) |>
  mutate(site = ifelse(site == "Montagne_tortue", "Montagne_Tortue", site)) |>
  # harmonize treatment information as logging and silvicultural treatments
  mutate(
    Treatment = ifelse(Treatment != "", Treatment, NA),
    logging = !grepl(control_string, tolower(Treatment)),
    silv_treat = grepl(silv_string, tolower(Treatment)),
    year_log = ifelse(site == "Paracou", 1986,
      Year_of_harvest |> substr(1, 4) |> as.numeric()
    )
  ) |>
  select(site, plot, logging, silv_treat, year_log)
```

```{r}
#| message: false
#| warning: false
data |>
  merge(plot_info, by.x = c("Site", "Plot"), by.y = c("site", "plot")) |>
  subset(variable %in% c("ba_growth", "ba_recr")) |>
  subset(Site %in% c("Mbaiki", "Paracou", "Ulu Muda", "Misiones")) |>
  pivot_wider(names_from = "variable") |>
  ggplot(aes(Year, ba_recr + ba_growth, ,
    group = Plot,
    col = ifelse(logging, "Logged", "Control")
  )) +
  geom_point() +
  geom_line() +
  labs(y = "Productivity [Mg/ha/yr]", col = NULL) +
  facet_wrap(~Site, scales = "free") +
  theme_minimal()
```
