```{r setup}
#| message: false
#| warning: false
#| include: false

library(tidyverse)
library(cmdstanr)
library(bayesplot)
library(patchwork)
list.files("r", full.names = TRUE, pattern = ".R") %>%
  lapply(source)
```

# Calibrate the model with forest inventory data {.unnumbered}

## Data

```{r}
control_string <- "unlogged|to be logged|old-growth|control|natural"
silv_string <- "treatment|devital|thinning"

plot_info <-
  read.csv("data/raw_data/bioforest-plot-information.csv") |>
  mutate(site = ifelse(site == "BAFOG", "Bafog", site)) |>
  mutate(site = ifelse(site == "Montagne_tortue", "Montagne_Tortue", site)) |>
  # harmonize treatment information as logging and silvicultural treatments
  mutate(
    Treatment = ifelse(Treatment != "", Treatment, NA),
    logging = !grepl(control_string, tolower(Treatment)),
    silv_treat = grepl(silv_string, tolower(Treatment)),
    year_log = ifelse(site == "Paracou", 1986,
      Year_of_harvest |> substr(1, 4) |> as.numeric()
    )
  ) |>
  select(site, plot, logging, silv_treat, year_log)

data <- read.csv("data/derived_data/aggregated_data.csv") |>
  subset(Site %in% c(
    "Lesong", "Mbaiki", "Misiones", "Moju", "Paracou",
    "Sg Lalang", "Ulu Muda"
  )) |>
  subset(variable %in% c("ba_mort", "ba_growth", "ba_recr", "ba")) |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  mutate(prod = ba_growth + ba_recr, mort = ba_mort, stocks = ba) |>
  select(!contains("ba")) |>
  pivot_longer(cols = c("stocks", "prod", "mort"), names_to = "variable") |>
  merge(plot_info, by.x = c("Site", "Plot"), by.y = c("site", "plot")) |>
  mutate(trec = Year - year_log) |>
  subset(!logging | !is.na(year_log))
```

```{r}
for (var in c("stocks", "prod", "mort")) {
  data |>
    subset(variable == var) |>
    ggplot(aes(trec, value)) +
    geom_point(aes(group = Plot, colour = Plot)) +
    geom_line(aes(group = Plot, colour = Plot)) +
    facet_wrap(~Site, scales = "free") +
    guides(colour = "none") +
    labs(y = var) +
    theme_minimal()
}
```

## Model

```{r}
bounds <- data.frame(
  "mu_thetaInf_min" = 0.01,
  "mu_thetaInf_max" = 1,
  "thetaInf_min" = 0.01,
  "thetaInf_max" = 5,
  "lambda_min" = 1e-3,
  "lambda_max" = 1,
  "dist_min" = 1e-2,
  "dist_max" = 1,
  "delta_min" = 0,
  "delta_max" = 1,
  "tau_min" = 2,
  "tau_max" = 30,
  "omega_min" = 1e-3,
  "omega_max" = 0.5,
  "y0_min" = 1,
  "y0_max" = 30
)
```

```{r}
data_rec <- data |>
  subset(logging & trec > 3) |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  subset(!is.na(prod) & !is.na(mort)) |>
  mutate(sitenum = as.numeric(as.factor(Site))) |>
  mutate(plotnum = as.numeric(as.factor(paste(Site, Plot))))
data_old <- data |>
  subset(!logging) |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  subset(!is.na(prod) & !is.na(mort)) |>
  mutate(sitenum = as.numeric(as.factor(Site)))
data_pre <- data |>
  subset(logging & trec < 0) |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  subset(!is.na(prod) & !is.na(mort)) |>
  mutate(sitenum = as.numeric(as.factor(Site)))
```

```{r fit_flux_model}
#| eval: false
ind_rec <- data_rec |>
  select(Site, Plot, sitenum, plotnum) |>
  unique() |>
  arrange(plotnum)

mdata <- list(
  n_rec = nrow(data_rec),
  n_old = nrow(data_old),
  n_pre = nrow(data_pre),
  n_site = max(data_rec$sitenum),
  n_plot_rec = max(data_rec$plotnum),
  y_rec = data_rec$stocks,
  y_old = data_old$stocks,
  y_pre = data_pre$stocks,
  in_rec = data_rec$prod,
  in_old = data_old$prod,
  in_pre = data_pre$prod,
  out_rec = data_rec$mort,
  out_old = data_old$mort,
  out_pre = data_pre$mort,
  time = data_rec$trec - 3,
  site_rec = data_rec$sitenum,
  site_old = data_old$sitenum,
  site_pre = data_pre$sitenum,
  plot_rec = data_rec$plotnum,
  site_plot_rec = ind_rec$sitenum,
  mu_thetaInf_bounds = c(
    bounds$mu_thetaInf_min,
    bounds$mu_thetaInf_max
  ),
  thetaInf_bounds = c(
    bounds$thetaInf_min,
    bounds$thetaInf_max
  ),
  lambda_bounds = c(
    bounds$lambda_min,
    bounds$lambda_max
  ),
  dist_bounds = c(
    bounds$dist_min,
    bounds$dist_max
  ),
  delta_bounds = c(
    bounds$delta_min,
    bounds$delta_max
  ),
  tau_bounds = c(
    bounds$tau_min,
    bounds$tau_max
  ),
  omega_bounds = c(
    bounds$omega_min,
    bounds$omega_max
  ),
  y0_bounds = c(
    bounds$y0_min,
    bounds$y0_max
  )
)

sample_model("flux", mdata)
```

```{r}
#| message: false
#| warning: false

fit_flux <- as_cmdstan_fit(list.files("chains/flux", full.names = TRUE))
fit_flux
```

```{r}
c("mu_dist", "mu_thetaInf", "mu_delta", "mu_lambda", "mu_omega") |>
  fit_flux$summary()
```

```{r}
#| warning: false
#| fig-cap: "Predicted vs observed values."
#| fig-width: 8
#| fig-height: 3

pred_data <- data_rec |>
  mutate(
    stocks = fit_flux$summary(c("mu_y_rec"), median)$median,
    prod = fit_flux$summary(c("mu_in_rec"), median)$median,
    mort = fit_flux$summary(c("mu_out_rec"), median)$median,
    val = "pred",
    type = "rec"
  ) |>
  select(-plotnum) |>
  rbind(mutate(
    data_pre,
    stocks = fit_flux$summary(c("mu_y_pre"), median)$median,
    prod = fit_flux$summary(c("mu_in_pre"), median)$median,
    mort = fit_flux$summary(c("mu_out_pre"), median)$median,
    val = "pred",
    type = "old"
  )) |>
  rbind(mutate(
    data_old,
    stocks = fit_flux$summary(c("mu_y_old"), median)$median,
    prod = fit_flux$summary(c("mu_in_old"), median)$median,
    mort = fit_flux$summary(c("mu_out_old"), median)$median,
    val = "pred",
    type = "old"
  ))

obs_data <- data_rec |>
  mutate(
    val = "obs",
    type = "rec"
  ) |>
  select(-plotnum) |>
  rbind(mutate(
    data_pre,
    val = "obs",
    type = "old"
  )) |>
  rbind(mutate(
    data_old,
    val = "obs",
    type = "old"
  ))

pov_data <- rbind(pred_data, obs_data) |>
  pivot_longer(cols = c(stocks, prod, mort), names_to = "variable") |>
  pivot_wider(names_from = val, values_from = value)

df_rmse <- pov_data |>
  group_by(variable) |>
  summarise(rmse = sqrt(mean((pred - obs)^2)))

pov_data |>
  ggplot(aes(pred, obs)) +
  geom_point(alpha = 0.25, aes(col = type)) +
  geom_abline(col = "red", linetype = "dashed") +
  geom_text(
    data = df_rmse,
    aes(
      x = -Inf, y = Inf, hjust = -0.1, vjust = 1,
      label = paste("RMSE =", round(rmse, 2))
    )
  ) +
  theme_bw() +
  xlab("Predicted") +
  ylab("Observed") +
  facet_wrap(~variable, scales = "free")
```
