project:
  type: book
  output-dir: docs

book:
  title: "demography"
  date: last-modified
  chapters:
    - index.qmd
    - 11_general_framework.qmd
    - part: 20_flux_model.qmd
      chapters:
        - 21_productivity.qmd
        - 22_mortality.qmd
        - 23_stocks_cst_mortality.qmd
        - 24_stocks_prop_mortality.qmd
        - 25_calibrate_flux_model.qmd
  appendices:
    - 91_ipp.qmd
    - 92_diff_equa.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual

# execute:
#   cache: true
