project:
  type: book
  output-dir: docs

book:
  title: "demography"
  date: last-modified
  chapters:
    - index.qmd
    - 11_general_framework.qmd
    - part: 20_flux_model.qmd
      chapters:
        - 21_flux_data.qmd
        - 22_flux_model.qmd
        - 23_calibrate_flux_model.qmd
        - 24_expl_variables.qmd
    - part: 30_cwd_flux.qmd
      chapters:
        - 31_cwd_productivity.qmd
  appendices:
    - 91_ipp.qmd
    - 92_diff_equa.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual

# execute:
#   cache: true
